"""empty message

Revision ID: 3e10b4c77c97
Revises: 6a6305ec8977
Create Date: 2022-02-05 15:46:27.345252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e10b4c77c97'
down_revision = '6a6305ec8977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_content', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_index('ix_book_info_book_name', table_name='book_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_book_info_book_name', 'book_info', ['book_name'], unique=False)
    op.drop_column('book_content', 'title')
    # ### end Alembic commands ###
