"""empty message

Revision ID: 6a6305ec8977
Revises: 
Create Date: 2022-02-05 12:15:39.599274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6305ec8977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_content',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_content_content'), 'book_content', ['content'], unique=True)
    op.create_table('book_info',
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('book_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_info_book_name'), 'book_info', ['book_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_info_book_name'), table_name='book_info')
    op.drop_table('book_info')
    op.drop_index(op.f('ix_book_content_content'), table_name='book_content')
    op.drop_table('book_content')
    # ### end Alembic commands ###
