"""empty message

Revision ID: bf69c1368c87
Revises: 3e10b4c77c97
Create Date: 2022-02-05 15:47:02.370482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf69c1368c87'
down_revision = '3e10b4c77c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_content', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_content', sa.Column('title', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
